# Generated by Django 4.1.7 on 2023-03-29 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_site_group_alter_site_support_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='support_user',
            field=models.ManyToManyField(related_name='supported_sites', to=settings.AUTH_USER_MODEL),
        ),
    ]
