# Generated by Django 4.1.7 on 2023-03-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_site_support_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='group',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='support_user',
            new_name='support_users',
        ),
    ]
