# Generated by Django 4.1.7 on 2023-03-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_group_site_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='groups',
        ),
        migrations.AddField(
            model_name='site',
            name='groups',
            field=models.ManyToManyField(related_name='group_sites', to='account.customgroup'),
        ),
    ]
