# Generated by Django 4.1.7 on 2023-03-22 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customgroup_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_code',
            field=models.CharField(default=uuid.uuid4, max_length=128),
        ),
    ]
