# Generated by Django 4.1.7 on 2023-03-29 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_cerated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'offline'), (1, 'online')], default=0)),
                ('remove', models.IntegerField(choices=[(0, 'unremoved'), (1, 'removed')], default=0)),
                ('ticket', models.IntegerField(default=0)),
                ('unique_code', models.CharField(default=uuid.uuid4, max_length=10)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_users', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='account.customgroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customsession')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.site')),
                ('suporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suporters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_cerated', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('remove', models.IntegerField(default=0)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.message')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account.customsession')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
