# Generated by Django 4.1.7 on 2023-02-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_groupchat_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='unique_code',
            field=models.CharField(max_length=10),
        ),
    ]
